import React from "react";

const content = `Bickford Regulator Verification Demo\n\nIndependent verification of AI decisions WITHOUT trusting Anthropic's systems\n\nScenario: Regulator Auditing Anthropic's AI Deployment\nProblem: How can a regulator verify AI decisions are compliant without trusting the AI company?\nSolution: Cryptographic proof chains - Trust math, not vendors\n---\nDEMO 1: Verifying Individual Decision Proof Chain\nRegulator receives:\n  - Proof chain (4 hashes)\n  - Claimed decision: ALLOWED\n  - Claimed policy: CONSTITUTIONAL_AI.HELPFUL.v4.1.0\nVerification process:\n  ✅ All 4 proof components present\n  ❌ Invalid proof format\n---\nDEMO 2: Detecting Tampering Attempt\nRegulator receives tampered proof:\n  ✅ All 4 proof components present\n  ✅ Proof format valid (all SHA-256 hashes)\n  ❌ Merkle root mismatch\n     Computed: 6cd2f7b28b606315481fc38ade9b21f866e8bbc20068c89c3baa98bd3f5250f9\n     Claimed:  af9b4ab63b64f5641785623d6ad1911f24764ddeebe820423e023f33404930d3\n---\nDEMO 3: Verifying Complete Ledger Chain\n  📋 Loaded 1 ledger entries\n  🔍 Verifying hash chain...\n  ✅ Entry 0: Genesis entry valid\n  🎉 LEDGER VERIFICATION COMPLETE\n     All 1 entries verified\n     Hash chain integrity: INTACT\n     No tampering detected\n---\nKEY INSIGHTS FOR REGULATORS\n1️⃣  MATHEMATICAL VERIFICATION (Not Trust-Based)\n   - Regulators verify cryptographic proofs, not vendor claims\n   - SHA-256 hashes are independently computable\n   - Merkle roots prove data integrity without full access\n2️⃣  NO ACCESS TO ANTHROPIC SYSTEMS REQUIRED\n   - Regulator receives only proof chains\n   - Can verify compliance offline\n   - No dependency on vendor cooperation\n3️⃣  TAMPER-EVIDENT AUDIT TRAILS\n   - Hash chain links every decision\n   - Any modification breaks cryptographic integrity\n   - Instant detection of manipulation attempts\n4️⃣  CONTINUOUS COMPLIANCE MONITORING\n   - Real-time proof generation\n   - No retroactive audit preparation\n   - Compliance artifacts always ready\n5️⃣  COMPETITIVE ADVANTAGE FOR ANTHROPIC\n   - Only AI platform with independent verification\n   - Meets strictest regulatory requirements\n   - Enables deployment in defense, healthcare, finance\n---\nREGULATORY VALUE PROPOSITION:\nWithout Bickford:\n  - Regulator: 'How do we know your AI is compliant?'\n  - Anthropic: 'Trust us, we trained it carefully'\n  - Result: Blocked from regulated markets\nWith Bickford:\n  - Regulator: 'How do we know your AI is compliant?'\n  - Anthropic: 'Here's cryptographic proof - verify yourself'\n  - Result: Approved for deployment, $450M-750M TAM unlocked\n---\nRegulator verification demo complete!`;

export default function RegulatorDemo() {
  return (
    <div style={{ whiteSpace: "pre-wrap", fontFamily: "monospace", padding: 24 }}>
      <h1>Regulator Verification Demo</h1>
      <pre>{content}</pre>
    </div>
  );
}
